### ISSUE TITLE
Missing Source Code Files

### ISSUE THREAD

**Issue by tlawrence3** [BCV-Uniandes/AMPs-Net#1]
Hi,
I just finished reading your recent article `Rational Discovery of Antimicrobial Peptides by Means of Artificial Intelligence` and was directed to this GitHub repo to find the source code and pretrained networks. However, it doesn't seem to be available yet.

Thanks,
Travis Lawrence

**Comment by somayeh-ebrah** [comment]
> Hi, I just finished reading your recent article `Rational Discovery of Antimicrobial Peptides by Means of Artificial Intelligence` and was directed to this GitHub repo to find the source code and pretrained networks. However, it doesn't seem to be available yet.
> 
> Thanks, Travis Lawrence

@tlawrence3 I have the same issue, 

@parbela @PaolaRuizP @cigonzalez Thanks for your nice work. 
Is it possible to share more about the data, the preprocessing of data, and the codes?

**Comment by PaolaRuizP** [comment]
Hi all, the source code will be in this repository over the weekend.

**Comment by PaolaRuizP** [comment]
Hi all, the code is now avaliable.
